Traceback (most recent call last):
  File "/teamspace/studios/this_studio/main.py", line 12, in <module>
    area = segment_wound_area(config)
  File "/teamspace/studios/this_studio/tasks/segment_wound_area.py", line 29, in segment_wound_area
    for image_path, gt_path in image_paths, gt_paths:
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/main.py", line 12, in <module>
    area = segment_wound_area(config)
  File "/teamspace/studios/this_studio/tasks/segment_wound_area.py", line 29, in segment_wound_area
    for image_path, gt_path in image_paths, gt_paths:
ValueError: too many values to unpack (expected 2)
