Traceback (most recent call last):
  File "/teamspace/studios/this_studio/main.py", line 12, in <module>
    area = segment_wound_area(config)
  File "/teamspace/studios/this_studio/tasks/segment_wound_area.py", line 35, in segment_wound_area
    compare = Image(compare_vis(config, gt, mask))
TypeError: 'module' object is not callable
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/main.py", line 12, in <module>
    area = segment_wound_area(config)
  File "/teamspace/studios/this_studio/tasks/segment_wound_area.py", line 35, in segment_wound_area
    compare = Image(compare_vis(config, gt, mask))
TypeError: 'module' object is not callable
